export { Home } from './Home';
export { Login } from './Login';
export { Register } from './Register';
export { Menu } from './Menu';
export { Cart } from './Cart';
export { PostPurchase } from './PostPurchase';
export { AdminPage } from './AdminPage';
export { User } from './User';
export { ChooseTypePizza } from './ChooseTypePizza';
